### PR TITLE
Update jet version

### PR DESCRIPTION
**Pull request by seeward**

### CODE REVIEW

**Review by mp3monster — COMMENTED** [review]
would be cool to format out across lines

**Review by mp3monster — APPROVED** [review]

**Review by mp3monster — APPROVED** [review]

**Review by mp3monster — APPROVED** [review]

**Review by mp3monster — APPROVED** [review]

**Review by mp3monster — APPROVED** [review]

**Review by mp3monster — APPROVED** [review]

**Comment by mp3monster** [comment]
changes bring alta UI and JET 7 -> 8

**Review by mp3monster — APPROVED** [review]
all changes look fine

**Review by mp3monster — APPROVED** [review]
approved

**Review by AntondegSTX — APPROVED** [review]

**Pull request merged**
